[package]
name = "hellogba"
version = "0.1.0"
authors = ["zerasul <zerasul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba={path="../gba"}

[[bin]]

name="hellogba"
path="src/hellogba.rs"